### PR TITLE
Introduce compatibility with ghc < 7.6.

### PR DESCRIPTION
**Pull request by qnikst**
This commit fixes test, so it will be possible to
compile them on older ghc.

### CODE REVIEW

**Comment by mboes** [comment]
More like "restore". I don't see why the old code wouldn't compile though. What's the fix?

**Comment by qnikst** [comment]
ErrorCall had no Eq instance in base-4.6 and lower, so I've used pattern matching here

**Comment by mboes** [comment]
nit: use a let form.

**Comment by mboes** [comment]
fixed.

**Comment by qnikst** [comment]
Thanks

**Pull request merged**
